import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

function updateDeployments(key: string, address: string) {
	let data: Record<string, string | null> = { evm: null, pvm: null };
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}
	data[key] = address;

	// Write JSON (for CLI and other tools)
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	// Write TypeScript (for frontend)
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null } = ${JSON.stringify(data, null, 2)};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying ProofOfExistence (EVM/solc)...");
	const poe = await hre.viem.deployContract("ProofOfExistence");
	console.log(`EVM ProofOfExistence deployed to: ${poe.address}`);
	updateDeployments("evm", poe.address);
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
