[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
chain = "./chain_spec.json"
cumulus_based = true

  [[parachains.collators]]
  name = "collator-01"
  validator = true
  command = "polkadot-omni-node"
  args = ["--enable-statement-store"]

  [[parachains.collators]]
  name = "collator-02"
  validator = true
  command = "polkadot-omni-node"
  args = ["--enable-statement-store"]
